name: Deploy Saguaro
on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: Changed Files
        id: changed-files-specific
        uses: tj-actions/changed-files@v45.0.3
        with:
          since_last_remote_commit: true
          files: |
            alembic/versions/*.py
      - name: check intactness of migrations
        if: steps.changed-files-specific.outputs.any_changed == 'true'
        run: |
          echo "Migration files are not allowed to change. List all the files that have changed: ${{ steps.changed-files-specific.outputs.all_changed_files }}"
          exit 1

  deploy-on-guru:
    runs-on: ubuntu-latest
    needs: test
    env:
      remote_host: ${{ secrets.GURU_USER }}@${{ secrets.GURU_HOST }}
      project: Saguaro
    steps:
      - uses: actions/checkout@v4
      
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.GURU_SSH_KEY }}
          known_hosts: ${{ secrets.GURU_KNOWN_HOST }}

      - name: Deploy with rsync
        run: rsync -avz --exclude-from='.rsyncignore' ./ ${{ env.remote_host }}:/home/ali/${{ env.project }}/



      - name: Check Cache Hit and Install Dependencies
        run: |
          ssh -vvv -T ${{ env.remote_host }} <<'ENDSSH'
          cd /home/ali/${{ env.project }}/ && source venv/bin/activate
          pip install -r requirements.txt
          ENDSSH

      - name: run migrations and restart app
        run: |
          ssh -vvv -T ${{ env.remote_host }} <<'ENDSSH'
          cd /home/ali/${{ env.project }}/ && source venv/bin/activate
          alembic upgrade head
          sudo systemctl restart saguaro.service
          ENDSSH

      - name: pull migration files
        run: |
          rsync -avrz --relative --exclude '__pycache__' --ignore-existing ${{ env.remote_host }}:/home/ali/${{ env.project }}/alembic/versions ./
          if [[ -n $(git status -s) ]]; then
            git config --global user.name 'Github action';
            git config --global user.email '111229965+alieskandari1@users.noreply.github.com';
            git add . && git commit -am "Added production migration files" && git push;
          fi 

